DATA:
    ROOT: '/workspace/ucf_reorganized'
    TRAIN_FILE: 'labels/UCF_train.txt'
    VAL_FILE: 'labels/UCF_test.txt'
    DATASET: ucf
    NUM_CLIPS: 16
    NUM_FRAMES: 5
    FRAME_INTERVAL: 6
    NUM_CLASSES: 2
    NUM_WORKERS: 32
    LABEL_LIST: 'labels/ucf_2_labels.csv'
    FILENAME_TMPL: 'img_{:08}.jpg'
    FILE_MODE: 'video'

MODEL:
    ARCH: ViT-B/32
    RESUME: '/workspace/umil/output/ucf/ckpt_epoch_24.pth'

TRAIN:
    BATCH_SIZE: 1
    ACCUMULATION_STEPS: 2
    BATCH_SIZE_UMIL: 1

MIL_SAVE_FREQ: 1
UMIL_SAVE_FREQ: 1