DATA:
    ROOT: '/workspace/tad/'
    TRAIN_FILE: 'labels/TAD_train.txt'
    VAL_FILE: 'labels/TAD_test.txt'
    DATASET: traffic
    NUM_CLIPS: 16
    NUM_FRAMES: 5
    FRAME_INTERVAL: 6
    NUM_CLASSES: 2
    NUM_WORKERS: 8
    LABEL_LIST: 'labels/traffic_2_labels.csv'
    FILENAME_TMPL: 'img_{:08}.jpg'
    FILE_MODE: 'video'

MODEL:
    ARCH: ViT-B/32
TRAIN:
    BATCH_SIZE: 2
    ACCUMULATION_STEPS: 8